on:
  push:
    tags:
      - 'v\d+\.\d+\.\d+'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0
      - name: Derive Tag Name And Populate version.ts
        id: derive_tag
        run: |
          VERSION_FILE=extension/app/ts/version.ts
          TAG=$(basename "${{ github.ref }}")
          GIT_COMMIT_SHA="${{ github.sha }}"
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo export const gitCommitSha = \"$GIT_COMMIT_SHA\" > $VERSION_FILE
          echo export const version = \"${TAG#v}\" >> $VERSION_FILE
      - name: Build Extension
        working-directory: ./extension
        run: |
          docker image build --tag interceptor-extension .
          docker container create --name temp interceptor-extension
          docker container cp temp:/extension/interceptor.zip .
          docker container rm temp
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.derive_tag.outputs.tag }}
          release_name: ${{ steps.derive_tag.outputs.tag }}
          draft: false
          prerelease: false
      - name: Upload Extension to Release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./extension/interceptor.zip
          asset_name: interceptor-${{ steps.derive_tag.outputs.tag }}.zip
          asset_content_type: application/zip
